name: Python Matrix Strategy

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Define the runner for the build job

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Install Python 3.9

      - name: Verify Python installation
        run: |
          python --version
          pip --version
