name: Use Secret in Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  example:
    runs-on: ubuntu-latest  # Use ubuntu-latest as the runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use GitHub secret
        run: |
          echo "Using secret to authenticate with an external service"
          curl -H "Authorization: token ${{ secrets.SECRET }}" https://api.github.com/user
        # Here the secret is used as part of the authorization header in a curl request

