name: Secret Usage Workflow

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest  # Use ubuntu-latest as the runner
    
    steps:
      # Step to check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step to retrieve and securely use the SECRET from GitHub secrets
      - name: Retrieve and use SECRET
        run: |
          echo "The SECRET is being used securely."
          # Accessing the secret without printing it
          echo "Secret is retrieved and ready for use."
          # For example, let's just use it to set an environment variable
          echo "MY_SECRET=${{ secrets.SECRET }}" >> $GITHUB_ENV
